# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build packages

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    # Rebuild everyday at midnight
    - cron:  '0 0 * * *'

jobs:
  build:
    env:
      cacheName: polypkgs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v30

    - name: Setup cachix
      uses: cachix/cachix-action@v16
      with:
        name: ${{ env.cacheName }}
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Build packages
      shell: sh
      run: |
        nix run github:Mic92/nix-fast-build -- \
          --flake ".#packages.$(nix eval --raw --impure --expr builtins.currentSystem)" \
          --no-nom \
          --skip-cached
